### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rivera-ernesto** [AlexanderMarchant/CodeLathe-Test#4]
Could you please take a look at this error:

> Build input files cannot be found: '/UIApplicationHelperService.swift', '/UIApplicationHelperServiceProtocol.swift' (in target 'CodeLathe-Test' from project 'CodeLathe-Test')

Feel free to commit a fix for it.

Thank you

**Comment by AlexanderMarchant** [comment]
@rivera-ernesto Hey, sorry! For some reason, the service was not incorporated in the Git Repository on init.

I have now added it into the repo.

Apologies for the hassle!
